### ISSUE TITLE
Can't see chat screen

### ISSUE THREAD

**Issue by Jaideep25** [McTechie/techie-firebase-chat#1]
If I login the screen is blank, using edge latest version, 
![image](https://user-images.githubusercontent.com/67269475/131697086-053eefd1-68a3-4b3a-b001-b4a82aa9f460.png)

Will be waiting for your reply !!
Thanks!

**Comment by McTechie** [comment]
Heyy @Jaideep25 is your browser possibly blocking third-party cookies? If so, enabling that would work xD

**Comment by Jaideep25** [comment]
![image](https://user-images.githubusercontent.com/67269475/131774335-5ae84a33-44f2-41ff-a15a-d6cd3834c86b.png)
Doesn't look like a cookie issue, but you can still go through the ss ;)

**Comment by McTechie** [comment]
Ahh well, I've tried using multiple accounts on Chrome as well as on Edge and it seemed to work just fine 😅
Could you also try this out on Chrome and let me know if the issue persists...??

**Comment by Jaideep25** [comment]
![image](https://user-images.githubusercontent.com/67269475/132080527-1fec8c9c-2153-4276-a4a5-7e0e655c06ef.png)
No luck 😕

**Comment by Jaideep25** [comment]
Hey @McTechie ! Got some good news! It worked ;) 
![image](https://user-images.githubusercontent.com/67269475/137880815-72436566-2560-4e5d-9495-3b97984dc848.png)

**Comment by Jaideep25** [comment]
![image](https://user-images.githubusercontent.com/67269475/137886034-8c7cb33b-29ac-4a9f-88d3-4023a9ed8bed.png)
Any idea why am I getting this? It's open on localhost :)
Thanks! Sorry for the trouble!
